### ISSUE TITLE
Updating MediaInfo.dll

### ISSUE THREAD

**Issue by hrxn** [stax76/Get-MediaInfo#13]
Hey, first of all, this works great and I really think this is an essential tool for every PowerShell user!

The current version of Get-MediaInfo as distributed on `powershellgallery.com` (version 3.7) contains `MediaInfo.dll` Version 21.03, 2021-03-26.

The latest version as of writing this is Version 22.06, can I just download the latest DLL from https://mediaarea.net/en/MediaInfo and replace the existing `MediaInfo.dll` to update? 
Or do I need a specific version of `MediaInfoSharp.dll` for this?

**Comment by stax76** [comment]
Thanks for the feedback. It should not be a problem, replacing MediaInfo.dll.
