### ISSUE TITLE
Proposal: Have all data in objects

### ISSUE THREAD

**Issue by vonpelz** [stax76/Get-MediaInfo#3]
At the moment Get-MediaInfo returns an object, but is lacking in data in comparison to Get-MediaInfoSummary. However, Get-MediaInfoSummary returns data in string format, which is not easy to work with.

I propose that all data returned from the Cmdlets should be in object form.

**Comment by stax76** [comment]
I'm not convinced, you can adjust it according your needs.

**Comment by vonpelz** [comment]
Thank you for your consideration. Any pointers what to look for to add more properties to `Get-MediaInfo`?  At the moment I'm studying `MediaInfoSharp.cs` and `Get-MediaInfo.ps1`.

**Comment by stax76** [comment]
These are the two main files, together only 340 lines of code, my smallest project.

**Comment by vonpelz** [comment]
Thank you, I'll try to look into it when I have the time. Meanwhile I accomplished what I wanted with following crude code (which was to find audio tracks and language):

```
$mediaInfoFull = Get-MediaInfoSummary -Path $file

$audioTracks = @()

$audioInfo = $mediaInfoFull | Select-String -Pattern 'Audio #' -Context 16

$audioInfo | ForEach-Object {

    $id = (($_.Context.DisplayPostContext | Select-String -Pattern 'ID')[0] -split ': ')[-1]
    $language = (($_.Context.DisplayPostContext | Select-String -Pattern 'Language') -split ': ')[-1]
    $audioTracks += [pscustomobject]@{id=$id;Language=$language}
}
```

**Comment by stax76** [comment]
For this kind of work I suggest [Get-MediaInfoValue](https://github.com/stax76/Get-MediaInfo#get-mediainfovalue), it requires some basic understanding how the MediaInfo API works, the API is however super simple and straightforward. If there are many files than using the .NET class directly is faster. I can help if you cannot find something.
