### ISSUE TITLE
Paths should be passed using the LiteralPath parameter

### ISSUE THREAD

**Issue by fredskis** [stax76/Get-MediaInfo#4]
Currently Cmdlets such as Convert-Path, Test-Path, Get-Item, Get-Content, Out-File all implicitly pass a parameter. This implies the -Path parameter and creates issues when dealing with files including characters with special functions within strings in PowerShell, e.g. []

I suggest at the very least explicitly defining all parameters rather than relying on positional or default implicit assignment.  Secondly, the Path should be passed with the -LiteralPath parameter instead of -Path. 

I've fixed this locally, will look at making my first contribution shortly :)

**Comment by stax76** [comment]
Thanks for the feedback. I'll take a look later, working currently on staxrip.

**Comment by stax76** [comment]
Thanks for the contribution and sorry about the delay.
