### ISSUE TITLE
Get-MedaInfoValue only returns first value

### ISSUE THREAD

**Issue by JustSomeGuyNZ** [stax76/Get-MediaInfo#7]
When using Get-MediaInfoValue to retrieve a specific item, such as audio language, if the container has multiple audio tracks it only returns the response for the first track.

For example, the following file has Italian and English audio when viewed by Get-MediaInfoSummary 
> Audio #1
>ID                                       : 2
>Format                                   : AC-3
>Format/Info                              : Audio Coding 3
>...
>Language                                 : it
>Audio #2
>ID                                       : 3
>Format                                   : E-AC-3
>Format/Info                              : Enhanced AC-3
>...
>Language                                 : en

However Get-MediaInfoValue -Path $Filepath -Kind Audio -Parameter Language returns only "it", rather than both "it" and "en" as expected.

**Comment by stax76** [comment]
I think you can find the answer in the examples:

https://github.com/stax76/Get-MediaInfo#examples-1

**Comment by JustSomeGuyNZ** [comment]
Thanks for that @stax76
